//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DizzySasquatchsBeltstatcalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DizzySasquatchsBeltstatcalculator.Properties.ResourceEN", typeof(ResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accuracy ähnelt.
        /// </summary>
        internal static string Acc {
            get {
                return ResourceManager.GetString("Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Agility ähnelt.
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angel ähnelt.
        /// </summary>
        internal static string Angel {
            get {
                return ResourceManager.GetString("Angel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attack Speed ähnelt.
        /// </summary>
        internal static string AtkSpd {
            get {
                return ResourceManager.GetString("AtkSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Baphomet ähnelt.
        /// </summary>
        internal static string Baphomet {
            get {
                return ResourceManager.GetString("Baphomet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blight Ogre ähnelt.
        /// </summary>
        internal static string BlightOgre {
            get {
                return ResourceManager.GetString("BlightOgre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block Ratio ähnelt.
        /// </summary>
        internal static string BlockRatio {
            get {
                return ResourceManager.GetString("BlockRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blue Pixie ähnelt.
        /// </summary>
        internal static string BluePixie {
            get {
                return ResourceManager.GetString("BluePixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cast Speed ähnelt.
        /// </summary>
        internal static string CastSpd {
            get {
                return ResourceManager.GetString("CastSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cerberus ähnelt.
        /// </summary>
        internal static string Cerberus {
            get {
                return ResourceManager.GetString("Cerberus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crit Ratio ähnelt.
        /// </summary>
        internal static string CritRatio {
            get {
                return ResourceManager.GetString("CritRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Death Tyrant ähnelt.
        /// </summary>
        internal static string DeathTyrant {
            get {
                return ResourceManager.GetString("DeathTyrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dexterity ähnelt.
        /// </summary>
        internal static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drillbot ähnelt.
        /// </summary>
        internal static string Drillbot {
            get {
                return ResourceManager.GetString("Drillbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Evasion ähnelt.
        /// </summary>
        internal static string Eva {
            get {
                return ResourceManager.GetString("Eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Genie ähnelt.
        /// </summary>
        internal static string Genie {
            get {
                return ResourceManager.GetString("Genie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gnoll ähnelt.
        /// </summary>
        internal static string Gnoll {
            get {
                return ResourceManager.GetString("Gnoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Harpy ähnelt.
        /// </summary>
        internal static string Harpy {
            get {
                return ResourceManager.GetString("Harpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hawkman ähnelt.
        /// </summary>
        internal static string Hawkman {
            get {
                return ResourceManager.GetString("Hawkman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HPRegen ähnelt.
        /// </summary>
        internal static string HPRegen {
            get {
                return ResourceManager.GetString("HPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ice Maiden ähnelt.
        /// </summary>
        internal static string IceMaiden {
            get {
                return ResourceManager.GetString("IceMaiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ifrit ähnelt.
        /// </summary>
        internal static string Ifrit {
            get {
                return ResourceManager.GetString("Ifrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intelligence ähnelt.
        /// </summary>
        internal static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Accuracy ähnelt.
        /// </summary>
        internal static string KDS_Acc {
            get {
                return ResourceManager.GetString("KDS_Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Agility ähnelt.
        /// </summary>
        internal static string KDS_Agility {
            get {
                return ResourceManager.GetString("KDS_Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Attack Speed ähnelt.
        /// </summary>
        internal static string KDS_AtkSpd {
            get {
                return ResourceManager.GetString("KDS_AtkSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Cast Speed ähnelt.
        /// </summary>
        internal static string KDS_CastSpd {
            get {
                return ResourceManager.GetString("KDS_CastSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Crit Ratio ähnelt.
        /// </summary>
        internal static string KDS_CritRatio {
            get {
                return ResourceManager.GetString("KDS_CritRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Dexterity ähnelt.
        /// </summary>
        internal static string KDS_Dexterity {
            get {
                return ResourceManager.GetString("KDS_Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Evasion ähnelt.
        /// </summary>
        internal static string KDS_Eva {
            get {
                return ResourceManager.GetString("KDS_Eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Intelligence ähnelt.
        /// </summary>
        internal static string KDS_Intelligence {
            get {
                return ResourceManager.GetString("KDS_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: MAccuracy ähnelt.
        /// </summary>
        internal static string KDS_MAcc {
            get {
                return ResourceManager.GetString("KDS_MAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: MAttack ähnelt.
        /// </summary>
        internal static string KDS_MAtk {
            get {
                return ResourceManager.GetString("KDS_MAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: MDefense ähnelt.
        /// </summary>
        internal static string KDS_MDef {
            get {
                return ResourceManager.GetString("KDS_MDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: MPRegen ähnelt.
        /// </summary>
        internal static string KDS_MPRegen {
            get {
                return ResourceManager.GetString("KDS_MPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: PAttack ähnelt.
        /// </summary>
        internal static string KDS_PAtk {
            get {
                return ResourceManager.GetString("KDS_PAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: PDefense ähnelt.
        /// </summary>
        internal static string KDS_PDef {
            get {
                return ResourceManager.GetString("KDS_PDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Strength ähnelt.
        /// </summary>
        internal static string KDS_Strength {
            get {
                return ResourceManager.GetString("KDS_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Vitality ähnelt.
        /// </summary>
        internal static string KDS_Vitality {
            get {
                return ResourceManager.GetString("KDS_Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul: Vitality / Wisdom ähnelt.
        /// </summary>
        internal static string KDS_VitalityWisdom {
            get {
                return ResourceManager.GetString("KDS_VitalityWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kentauros ähnelt.
        /// </summary>
        internal static string Kentauros {
            get {
                return ResourceManager.GetString("Kentauros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luck ähnelt.
        /// </summary>
        internal static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lydian ähnelt.
        /// </summary>
        internal static string Lydian {
            get {
                return ResourceManager.GetString("Lydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MAccuracy ähnelt.
        /// </summary>
        internal static string MAcc {
            get {
                return ResourceManager.GetString("MAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MAttack ähnelt.
        /// </summary>
        internal static string MAtk {
            get {
                return ResourceManager.GetString("MAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MDefense ähnelt.
        /// </summary>
        internal static string MDef {
            get {
                return ResourceManager.GetString("MDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minotaurus ähnelt.
        /// </summary>
        internal static string Minotaurus {
            get {
                return ResourceManager.GetString("Minotaurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MPRegen ähnelt.
        /// </summary>
        internal static string MPRegen {
            get {
                return ResourceManager.GetString("MPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mystic Koala ähnelt.
        /// </summary>
        internal static string MysticKoala {
            get {
                return ResourceManager.GetString("MysticKoala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Naga ähnelt.
        /// </summary>
        internal static string Naga {
            get {
                return ResourceManager.GetString("Naga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nightmare ähnelt.
        /// </summary>
        internal static string Nightmare {
            get {
                return ResourceManager.GetString("Nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Octopus ähnelt.
        /// </summary>
        internal static string Octopus {
            get {
                return ResourceManager.GetString("Octopus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orc ähnelt.
        /// </summary>
        internal static string Orc {
            get {
                return ResourceManager.GetString("Orc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pantera ähnelt.
        /// </summary>
        internal static string Pantera {
            get {
                return ResourceManager.GetString("Pantera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PAttack ähnelt.
        /// </summary>
        internal static string PAtk {
            get {
                return ResourceManager.GetString("PAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDefense ähnelt.
        /// </summary>
        internal static string PDef {
            get {
                return ResourceManager.GetString("PDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Poultry ähnelt.
        /// </summary>
        internal static string Poultry {
            get {
                return ResourceManager.GetString("Poultry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red Pixie ähnelt.
        /// </summary>
        internal static string RedPixie {
            get {
                return ResourceManager.GetString("RedPixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Salamander ähnelt.
        /// </summary>
        internal static string Salamander {
            get {
                return ResourceManager.GetString("Salamander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Siren ähnelt.
        /// </summary>
        internal static string Siren {
            get {
                return ResourceManager.GetString("Siren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skeleton ähnelt.
        /// </summary>
        internal static string Skeleton {
            get {
                return ResourceManager.GetString("Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snowman ähnelt.
        /// </summary>
        internal static string Snowman {
            get {
                return ResourceManager.GetString("Snowman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stone Golem ähnelt.
        /// </summary>
        internal static string StoneGolem {
            get {
                return ResourceManager.GetString("StoneGolem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strength ähnelt.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tortus ähnelt.
        /// </summary>
        internal static string Tortus {
            get {
                return ResourceManager.GetString("Tortus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string UI_About {
            get {
                return ResourceManager.GetString("UI_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DizzySasquatch&apos;s Beltstatcalculator $version$n$nThanks to Grzlgrmpf, who helped me testing and made some nice suggestions. ähnelt.
        /// </summary>
        internal static string UI_AboutText {
            get {
                return ResourceManager.GetString("UI_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About the Beltstatcalculator (by DizzySasquatch) ähnelt.
        /// </summary>
        internal static string UI_AboutTitle {
            get {
                return ResourceManager.GetString("UI_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Belt Enhancement ähnelt.
        /// </summary>
        internal static string UI_BeltEnhancement {
            get {
                return ResourceManager.GetString("UI_BeltEnhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string UI_Error {
            get {
                return ResourceManager.GetString("UI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error parsing language. ähnelt.
        /// </summary>
        internal static string UI_LanguageParseError {
            get {
                return ResourceManager.GetString("UI_LanguageParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limit ähnelt.
        /// </summary>
        internal static string UI_Limit {
            get {
                return ResourceManager.GetString("UI_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string UI_Reset {
            get {
                return ResourceManager.GetString("UI_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stage ähnelt.
        /// </summary>
        internal static string UI_Stage {
            get {
                return ResourceManager.GetString("UI_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undine ähnelt.
        /// </summary>
        internal static string Undine {
            get {
                return ResourceManager.GetString("Undine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unicorn ähnelt.
        /// </summary>
        internal static string Unicorn {
            get {
                return ResourceManager.GetString("Unicorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vitality ähnelt.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die White Dragon ähnelt.
        /// </summary>
        internal static string WhiteDragon {
            get {
                return ResourceManager.GetString("WhiteDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wisdom ähnelt.
        /// </summary>
        internal static string Wisdom {
            get {
                return ResourceManager.GetString("Wisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wolf ähnelt.
        /// </summary>
        internal static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yeti ähnelt.
        /// </summary>
        internal static string Yeti {
            get {
                return ResourceManager.GetString("Yeti", resourceCulture);
            }
        }
    }
}
