//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DizzySasquatchsBeltstatcalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DizzySasquatchsBeltstatcalculator.Properties.ResourceEN", typeof(ResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string Acc {
            get {
                return ResourceManager.GetString("Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angel.
        /// </summary>
        internal static string Angel {
            get {
                return ResourceManager.GetString("Angel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Speed.
        /// </summary>
        internal static string AtkSpd {
            get {
                return ResourceManager.GetString("AtkSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baphomet.
        /// </summary>
        internal static string Baphomet {
            get {
                return ResourceManager.GetString("Baphomet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blight Ogre.
        /// </summary>
        internal static string BlightOgre {
            get {
                return ResourceManager.GetString("BlightOgre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockDef.
        /// </summary>
        internal static string BlockDef {
            get {
                return ResourceManager.GetString("BlockDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Ratio.
        /// </summary>
        internal static string BlockRatio {
            get {
                return ResourceManager.GetString("BlockRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloodthirsty Slaughterer.
        /// </summary>
        internal static string BloodthirstySlaughterer {
            get {
                return ResourceManager.GetString("BloodthirstySlaughterer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Pixie.
        /// </summary>
        internal static string BluePixie {
            get {
                return ResourceManager.GetString("BluePixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast Speed.
        /// </summary>
        internal static string CastSpd {
            get {
                return ResourceManager.GetString("CastSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerberus.
        /// </summary>
        internal static string Cerberus {
            get {
                return ResourceManager.GetString("Cerberus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit Ratio.
        /// </summary>
        internal static string CritRatio {
            get {
                return ResourceManager.GetString("CritRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Golem.
        /// </summary>
        internal static string CrystalGolem {
            get {
                return ResourceManager.GetString("CrystalGolem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Spider.
        /// </summary>
        internal static string CrystalSpider {
            get {
                return ResourceManager.GetString("CrystalSpider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Gladiator.
        /// </summary>
        internal static string DeathGladiator {
            get {
                return ResourceManager.GetString("DeathGladiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Tyrant.
        /// </summary>
        internal static string DeathTyrant {
            get {
                return ResourceManager.GetString("DeathTyrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        internal static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drillbot.
        /// </summary>
        internal static string Drillbot {
            get {
                return ResourceManager.GetString("Drillbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethereal Pixie.
        /// </summary>
        internal static string EtherealPixie {
            get {
                return ResourceManager.GetString("EtherealPixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evasion.
        /// </summary>
        internal static string Eva {
            get {
                return ResourceManager.GetString("Eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Pixie.
        /// </summary>
        internal static string ForestPixie {
            get {
                return ResourceManager.GetString("ForestPixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genie.
        /// </summary>
        internal static string Genie {
            get {
                return ResourceManager.GetString("Genie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnoll.
        /// </summary>
        internal static string Gnoll {
            get {
                return ResourceManager.GetString("Gnoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandmaster Hector.
        /// </summary>
        internal static string GrandmasterHector {
            get {
                return ResourceManager.GetString("GrandmasterHector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harpy.
        /// </summary>
        internal static string Harpy {
            get {
                return ResourceManager.GetString("Harpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawkman.
        /// </summary>
        internal static string Hawkman {
            get {
                return ResourceManager.GetString("Hawkman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPRegen.
        /// </summary>
        internal static string HPRegen {
            get {
                return ResourceManager.GetString("HPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Maiden.
        /// </summary>
        internal static string IceMaiden {
            get {
                return ResourceManager.GetString("IceMaiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ifrit.
        /// </summary>
        internal static string Ifrit {
            get {
                return ResourceManager.GetString("Ifrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        internal static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Accuracy.
        /// </summary>
        internal static string KDS_Acc {
            get {
                return ResourceManager.GetString("KDS_Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Agility.
        /// </summary>
        internal static string KDS_Agility {
            get {
                return ResourceManager.GetString("KDS_Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Attack Speed.
        /// </summary>
        internal static string KDS_AtkSpd {
            get {
                return ResourceManager.GetString("KDS_AtkSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Cast Speed.
        /// </summary>
        internal static string KDS_CastSpd {
            get {
                return ResourceManager.GetString("KDS_CastSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Crit Ratio.
        /// </summary>
        internal static string KDS_CritRatio {
            get {
                return ResourceManager.GetString("KDS_CritRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Dexterity.
        /// </summary>
        internal static string KDS_Dexterity {
            get {
                return ResourceManager.GetString("KDS_Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Evasion.
        /// </summary>
        internal static string KDS_Eva {
            get {
                return ResourceManager.GetString("KDS_Eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Intelligence.
        /// </summary>
        internal static string KDS_Intelligence {
            get {
                return ResourceManager.GetString("KDS_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: MAccuracy.
        /// </summary>
        internal static string KDS_MAcc {
            get {
                return ResourceManager.GetString("KDS_MAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: MAttack.
        /// </summary>
        internal static string KDS_MAtk {
            get {
                return ResourceManager.GetString("KDS_MAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: MDefense.
        /// </summary>
        internal static string KDS_MDef {
            get {
                return ResourceManager.GetString("KDS_MDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: MPRegen.
        /// </summary>
        internal static string KDS_MPRegen {
            get {
                return ResourceManager.GetString("KDS_MPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: PAttack.
        /// </summary>
        internal static string KDS_PAtk {
            get {
                return ResourceManager.GetString("KDS_PAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: PDefense.
        /// </summary>
        internal static string KDS_PDef {
            get {
                return ResourceManager.GetString("KDS_PDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Strength.
        /// </summary>
        internal static string KDS_Strength {
            get {
                return ResourceManager.GetString("KDS_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Vitality.
        /// </summary>
        internal static string KDS_Vitality {
            get {
                return ResourceManager.GetString("KDS_Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul: Vitality / Wisdom.
        /// </summary>
        internal static string KDS_VitalityWisdom {
            get {
                return ResourceManager.GetString("KDS_VitalityWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kentauros.
        /// </summary>
        internal static string Kentauros {
            get {
                return ResourceManager.GetString("Kentauros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luck.
        /// </summary>
        internal static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lydian.
        /// </summary>
        internal static string Lydian {
            get {
                return ResourceManager.GetString("Lydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAccuracy.
        /// </summary>
        internal static string MAcc {
            get {
                return ResourceManager.GetString("MAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAttack.
        /// </summary>
        internal static string MAtk {
            get {
                return ResourceManager.GetString("MAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDefense.
        /// </summary>
        internal static string MDef {
            get {
                return ResourceManager.GetString("MDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minotaurus.
        /// </summary>
        internal static string Minotaurus {
            get {
                return ResourceManager.GetString("Minotaurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPRegen.
        /// </summary>
        internal static string MPRegen {
            get {
                return ResourceManager.GetString("MPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRes.
        /// </summary>
        internal static string MRes {
            get {
                return ResourceManager.GetString("MRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystic Koala.
        /// </summary>
        internal static string MysticKoala {
            get {
                return ResourceManager.GetString("MysticKoala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naga.
        /// </summary>
        internal static string Naga {
            get {
                return ResourceManager.GetString("Naga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightmare.
        /// </summary>
        internal static string Nightmare {
            get {
                return ResourceManager.GetString("Nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octopus.
        /// </summary>
        internal static string Octopus {
            get {
                return ResourceManager.GetString("Octopus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.
        /// </summary>
        internal static string Orc {
            get {
                return ResourceManager.GetString("Orc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pantera.
        /// </summary>
        internal static string Pantera {
            get {
                return ResourceManager.GetString("Pantera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAttack.
        /// </summary>
        internal static string PAtk {
            get {
                return ResourceManager.GetString("PAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDefense.
        /// </summary>
        internal static string PDef {
            get {
                return ResourceManager.GetString("PDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poultry.
        /// </summary>
        internal static string Poultry {
            get {
                return ResourceManager.GetString("Poultry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Pixie.
        /// </summary>
        internal static string RedPixie {
            get {
                return ResourceManager.GetString("RedPixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salamander.
        /// </summary>
        internal static string Salamander {
            get {
                return ResourceManager.GetString("Salamander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siren.
        /// </summary>
        internal static string Siren {
            get {
                return ResourceManager.GetString("Siren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton.
        /// </summary>
        internal static string Skeleton {
            get {
                return ResourceManager.GetString("Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowman.
        /// </summary>
        internal static string Snowman {
            get {
                return ResourceManager.GetString("Snowman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Golem.
        /// </summary>
        internal static string StoneGolem {
            get {
                return ResourceManager.GetString("StoneGolem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tortus.
        /// </summary>
        internal static string Tortus {
            get {
                return ResourceManager.GetString("Tortus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string UI_About {
            get {
                return ResourceManager.GetString("UI_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DizzySasquatch&apos;s Beltstatcalculator $version$n$nThanks to Grzlgrmpf, who helped me testing and made some nice suggestions.$n$nTranslators:$nGerman$t$tDizzySasquatch$nEnglish$t$tDizzySasquatch$nFrench$t$tSorrowAssa.
        /// </summary>
        internal static string UI_AboutText {
            get {
                return ResourceManager.GetString("UI_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Beltstatcalculator (by DizzySasquatch).
        /// </summary>
        internal static string UI_AboutTitle {
            get {
                return ResourceManager.GetString("UI_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belt Enhancement.
        /// </summary>
        internal static string UI_BeltEnhancement {
            get {
                return ResourceManager.GetString("UI_BeltEnhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string UI_Error {
            get {
                return ResourceManager.GetString("UI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing language..
        /// </summary>
        internal static string UI_LanguageParseError {
            get {
                return ResourceManager.GetString("UI_LanguageParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        internal static string UI_Limit {
            get {
                return ResourceManager.GetString("UI_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string UI_Reset {
            get {
                return ResourceManager.GetString("UI_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        internal static string UI_Stage {
            get {
                return ResourceManager.GetString("UI_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undine.
        /// </summary>
        internal static string Undine {
            get {
                return ResourceManager.GetString("Undine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicorn.
        /// </summary>
        internal static string Unicorn {
            get {
                return ResourceManager.GetString("Unicorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitality.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Dragon.
        /// </summary>
        internal static string WhiteDragon {
            get {
                return ResourceManager.GetString("WhiteDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Pixie.
        /// </summary>
        internal static string WindPixie {
            get {
                return ResourceManager.GetString("WindPixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        internal static string Wisdom {
            get {
                return ResourceManager.GetString("Wisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolf.
        /// </summary>
        internal static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeti.
        /// </summary>
        internal static string Yeti {
            get {
                return ResourceManager.GetString("Yeti", resourceCulture);
            }
        }
    }
}
