//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DizzySasquatchsBeltstatcalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DizzySasquatchsBeltstatcalculator.Properties.ResourceDE", typeof(ResourceDE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genauigkeit.
        /// </summary>
        internal static string Acc {
            get {
                return ResourceManager.GetString("Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewandtheit.
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engel.
        /// </summary>
        internal static string Angel {
            get {
                return ResourceManager.GetString("Angel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ang. Ges..
        /// </summary>
        internal static string AtkSpd {
            get {
                return ResourceManager.GetString("AtkSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baphomet.
        /// </summary>
        internal static string Baphomet {
            get {
                return ResourceManager.GetString("Baphomet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nargash.
        /// </summary>
        internal static string BlightOgre {
            get {
                return ResourceManager.GetString("BlightOgre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockrate.
        /// </summary>
        internal static string BlockRatio {
            get {
                return ResourceManager.GetString("BlockRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blaue Pixie.
        /// </summary>
        internal static string BluePixie {
            get {
                return ResourceManager.GetString("BluePixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zauber Ges..
        /// </summary>
        internal static string CastSpd {
            get {
                return ResourceManager.GetString("CastSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerberus.
        /// </summary>
        internal static string Cerberus {
            get {
                return ResourceManager.GetString("Cerberus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krit. Trefferch..
        /// </summary>
        internal static string CritRatio {
            get {
                return ResourceManager.GetString("CritRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todesritter.
        /// </summary>
        internal static string DeathTyrant {
            get {
                return ResourceManager.GetString("DeathTyrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschicklichkeit.
        /// </summary>
        internal static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr. Iller.
        /// </summary>
        internal static string Drillbot {
            get {
                return ResourceManager.GetString("Drillbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflex.
        /// </summary>
        internal static string Eva {
            get {
                return ResourceManager.GetString("Eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djinni.
        /// </summary>
        internal static string Genie {
            get {
                return ResourceManager.GetString("Genie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eimus.
        /// </summary>
        internal static string Gnoll {
            get {
                return ResourceManager.GetString("Gnoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harpie.
        /// </summary>
        internal static string Harpy {
            get {
                return ResourceManager.GetString("Harpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falkenmann.
        /// </summary>
        internal static string Hawkman {
            get {
                return ResourceManager.GetString("Hawkman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP Erh..
        /// </summary>
        internal static string HPRegen {
            get {
                return ResourceManager.GetString("HPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kainen.
        /// </summary>
        internal static string IceMaiden {
            get {
                return ResourceManager.GetString("IceMaiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystischer Djinni.
        /// </summary>
        internal static string Ifrit {
            get {
                return ResourceManager.GetString("Ifrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligenz.
        /// </summary>
        internal static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Genauigkeit.
        /// </summary>
        internal static string KDS_Acc {
            get {
                return ResourceManager.GetString("KDS_Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Gewandtheit.
        /// </summary>
        internal static string KDS_Agility {
            get {
                return ResourceManager.GetString("KDS_Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Ang. Ges..
        /// </summary>
        internal static string KDS_AtkSpd {
            get {
                return ResourceManager.GetString("KDS_AtkSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Zauber Ges..
        /// </summary>
        internal static string KDS_CastSpd {
            get {
                return ResourceManager.GetString("KDS_CastSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Krit. Trefferch..
        /// </summary>
        internal static string KDS_CritRatio {
            get {
                return ResourceManager.GetString("KDS_CritRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Geschicklichkeit.
        /// </summary>
        internal static string KDS_Dexterity {
            get {
                return ResourceManager.GetString("KDS_Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Reflex.
        /// </summary>
        internal static string KDS_Eva {
            get {
                return ResourceManager.GetString("KDS_Eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Intelligenz.
        /// </summary>
        internal static string KDS_Intelligence {
            get {
                return ResourceManager.GetString("KDS_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: M. Gen..
        /// </summary>
        internal static string KDS_MAcc {
            get {
                return ResourceManager.GetString("KDS_MAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: M. Angriff.
        /// </summary>
        internal static string KDS_MAtk {
            get {
                return ResourceManager.GetString("KDS_MAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: M. Abwehr.
        /// </summary>
        internal static string KDS_MDef {
            get {
                return ResourceManager.GetString("KDS_MDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: MP Erh..
        /// </summary>
        internal static string KDS_MPRegen {
            get {
                return ResourceManager.GetString("KDS_MPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: P. Angriff.
        /// </summary>
        internal static string KDS_PAtk {
            get {
                return ResourceManager.GetString("KDS_PAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: P. Abwehr.
        /// </summary>
        internal static string KDS_PDef {
            get {
                return ResourceManager.GetString("KDS_PDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Stärke.
        /// </summary>
        internal static string KDS_Strength {
            get {
                return ResourceManager.GetString("KDS_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Vitalität.
        /// </summary>
        internal static string KDS_Vitality {
            get {
                return ResourceManager.GetString("KDS_Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDS: Vitalität / Willenskraft.
        /// </summary>
        internal static string KDS_VitalityWisdom {
            get {
                return ResourceManager.GetString("KDS_VitalityWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenta.
        /// </summary>
        internal static string Kentauros {
            get {
                return ResourceManager.GetString("Kentauros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glück.
        /// </summary>
        internal static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lydian.
        /// </summary>
        internal static string Lydian {
            get {
                return ResourceManager.GetString("Lydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M. Gen..
        /// </summary>
        internal static string MAcc {
            get {
                return ResourceManager.GetString("MAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M. Angriff.
        /// </summary>
        internal static string MAtk {
            get {
                return ResourceManager.GetString("MAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M. Abwehr.
        /// </summary>
        internal static string MDef {
            get {
                return ResourceManager.GetString("MDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minotaurus.
        /// </summary>
        internal static string Minotaurus {
            get {
                return ResourceManager.GetString("Minotaurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP Erh..
        /// </summary>
        internal static string MPRegen {
            get {
                return ResourceManager.GetString("MPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karfunkel.
        /// </summary>
        internal static string MysticKoala {
            get {
                return ResourceManager.GetString("MysticKoala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tafari.
        /// </summary>
        internal static string Naga {
            get {
                return ResourceManager.GetString("Naga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachtmahr.
        /// </summary>
        internal static string Nightmare {
            get {
                return ResourceManager.GetString("Nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktopus.
        /// </summary>
        internal static string Octopus {
            get {
                return ResourceManager.GetString("Octopus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ork.
        /// </summary>
        internal static string Orc {
            get {
                return ResourceManager.GetString("Orc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panter.
        /// </summary>
        internal static string Pantera {
            get {
                return ResourceManager.GetString("Pantera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P. Angriff.
        /// </summary>
        internal static string PAtk {
            get {
                return ResourceManager.GetString("PAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P. Abwehr.
        /// </summary>
        internal static string PDef {
            get {
                return ResourceManager.GetString("PDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geflügel.
        /// </summary>
        internal static string Poultry {
            get {
                return ResourceManager.GetString("Poultry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rote Pixie.
        /// </summary>
        internal static string RedPixie {
            get {
                return ResourceManager.GetString("RedPixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salamander.
        /// </summary>
        internal static string Salamander {
            get {
                return ResourceManager.GetString("Salamander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sirene.
        /// </summary>
        internal static string Siren {
            get {
                return ResourceManager.GetString("Siren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skelett.
        /// </summary>
        internal static string Skeleton {
            get {
                return ResourceManager.GetString("Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schneemann.
        /// </summary>
        internal static string Snowman {
            get {
                return ResourceManager.GetString("Snowman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schicksalswürfel.
        /// </summary>
        internal static string StoneGolem {
            get {
                return ResourceManager.GetString("StoneGolem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stärke.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tortus.
        /// </summary>
        internal static string Tortus {
            get {
                return ResourceManager.GetString("Tortus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string UI_About {
            get {
                return ResourceManager.GetString("UI_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DizzySasquatch&apos;s Beltstatcalculator $version$n$nVielen Dank an Grzlgrmpf für die Hilfe beim Testen und Einbringen neuer Ideen.$n$nÜbersetzer:$nDeutsch$t$tDizzySasquatch$nEnglisch$t$tDizzySasquatch$nFranzösisch$tSorrowAssa.
        /// </summary>
        internal static string UI_AboutText {
            get {
                return ResourceManager.GetString("UI_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über den Beltstatcalculator (by DizzySasquatch).
        /// </summary>
        internal static string UI_AboutTitle {
            get {
                return ResourceManager.GetString("UI_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gürtelverzauberung.
        /// </summary>
        internal static string UI_BeltEnhancement {
            get {
                return ResourceManager.GetString("UI_BeltEnhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string UI_Error {
            get {
                return ResourceManager.GetString("UI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache konnte nicht geladen werden..
        /// </summary>
        internal static string UI_LanguageParseError {
            get {
                return ResourceManager.GetString("UI_LanguageParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        internal static string UI_Limit {
            get {
                return ResourceManager.GetString("UI_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        internal static string UI_Reset {
            get {
                return ResourceManager.GetString("UI_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraftstufe.
        /// </summary>
        internal static string UI_Stage {
            get {
                return ResourceManager.GetString("UI_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechapixie.
        /// </summary>
        internal static string Undine {
            get {
                return ResourceManager.GetString("Undine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einhorn.
        /// </summary>
        internal static string Unicorn {
            get {
                return ResourceManager.GetString("Unicorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalität.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weißer Drache.
        /// </summary>
        internal static string WhiteDragon {
            get {
                return ResourceManager.GetString("WhiteDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willenskraft.
        /// </summary>
        internal static string Wisdom {
            get {
                return ResourceManager.GetString("Wisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolf.
        /// </summary>
        internal static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeti.
        /// </summary>
        internal static string Yeti {
            get {
                return ResourceManager.GetString("Yeti", resourceCulture);
            }
        }
    }
}
