//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DizzySasquatchsBeltstatcalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DizzySasquatchsBeltstatcalculator.Properties.ResourceDE", typeof(ResourceDE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Genauigkeit ähnelt.
        /// </summary>
        internal static string Acc {
            get {
                return ResourceManager.GetString("Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gewandtheit ähnelt.
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engel ähnelt.
        /// </summary>
        internal static string Angel {
            get {
                return ResourceManager.GetString("Angel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ang. Ges. ähnelt.
        /// </summary>
        internal static string AtkSpd {
            get {
                return ResourceManager.GetString("AtkSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Baphomet ähnelt.
        /// </summary>
        internal static string Baphomet {
            get {
                return ResourceManager.GetString("Baphomet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nargash ähnelt.
        /// </summary>
        internal static string BlightOgre {
            get {
                return ResourceManager.GetString("BlightOgre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blockrate ähnelt.
        /// </summary>
        internal static string BlockRatio {
            get {
                return ResourceManager.GetString("BlockRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blaue Pixie ähnelt.
        /// </summary>
        internal static string BluePixie {
            get {
                return ResourceManager.GetString("BluePixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zauber Ges. ähnelt.
        /// </summary>
        internal static string CastSpd {
            get {
                return ResourceManager.GetString("CastSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cerberus ähnelt.
        /// </summary>
        internal static string Cerberus {
            get {
                return ResourceManager.GetString("Cerberus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Krit. Trefferch. ähnelt.
        /// </summary>
        internal static string CritRatio {
            get {
                return ResourceManager.GetString("CritRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Todesritter ähnelt.
        /// </summary>
        internal static string DeathTyrant {
            get {
                return ResourceManager.GetString("DeathTyrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschicklichkeit ähnelt.
        /// </summary>
        internal static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dr. Iller ähnelt.
        /// </summary>
        internal static string Drillbot {
            get {
                return ResourceManager.GetString("Drillbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reflex ähnelt.
        /// </summary>
        internal static string Eva {
            get {
                return ResourceManager.GetString("Eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Djinni ähnelt.
        /// </summary>
        internal static string Genie {
            get {
                return ResourceManager.GetString("Genie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eimus ähnelt.
        /// </summary>
        internal static string Gnoll {
            get {
                return ResourceManager.GetString("Gnoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Harpie ähnelt.
        /// </summary>
        internal static string Harpy {
            get {
                return ResourceManager.GetString("Harpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falkenmann ähnelt.
        /// </summary>
        internal static string Hawkman {
            get {
                return ResourceManager.GetString("Hawkman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HP Erh. ähnelt.
        /// </summary>
        internal static string HPRegen {
            get {
                return ResourceManager.GetString("HPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kainen ähnelt.
        /// </summary>
        internal static string IceMaiden {
            get {
                return ResourceManager.GetString("IceMaiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mystischer Djinni ähnelt.
        /// </summary>
        internal static string Ifrit {
            get {
                return ResourceManager.GetString("Ifrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intelligenz ähnelt.
        /// </summary>
        internal static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Genauigkeit ähnelt.
        /// </summary>
        internal static string KDS_Acc {
            get {
                return ResourceManager.GetString("KDS_Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Gewandtheit ähnelt.
        /// </summary>
        internal static string KDS_Agility {
            get {
                return ResourceManager.GetString("KDS_Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Ang. Ges. ähnelt.
        /// </summary>
        internal static string KDS_AtkSpd {
            get {
                return ResourceManager.GetString("KDS_AtkSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Zauber Ges. ähnelt.
        /// </summary>
        internal static string KDS_CastSpd {
            get {
                return ResourceManager.GetString("KDS_CastSpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Krit. Trefferch. ähnelt.
        /// </summary>
        internal static string KDS_CritRatio {
            get {
                return ResourceManager.GetString("KDS_CritRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Geschicklichkeit ähnelt.
        /// </summary>
        internal static string KDS_Dexterity {
            get {
                return ResourceManager.GetString("KDS_Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Reflex ähnelt.
        /// </summary>
        internal static string KDS_Eva {
            get {
                return ResourceManager.GetString("KDS_Eva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Intelligenz ähnelt.
        /// </summary>
        internal static string KDS_Intelligence {
            get {
                return ResourceManager.GetString("KDS_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: M. Gen. ähnelt.
        /// </summary>
        internal static string KDS_MAcc {
            get {
                return ResourceManager.GetString("KDS_MAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: M. Angriff ähnelt.
        /// </summary>
        internal static string KDS_MAtk {
            get {
                return ResourceManager.GetString("KDS_MAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: M. Abwehr ähnelt.
        /// </summary>
        internal static string KDS_MDef {
            get {
                return ResourceManager.GetString("KDS_MDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: MP Erh. ähnelt.
        /// </summary>
        internal static string KDS_MPRegen {
            get {
                return ResourceManager.GetString("KDS_MPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: P. Angriff ähnelt.
        /// </summary>
        internal static string KDS_PAtk {
            get {
                return ResourceManager.GetString("KDS_PAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: P. Abwehr ähnelt.
        /// </summary>
        internal static string KDS_PDef {
            get {
                return ResourceManager.GetString("KDS_PDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Stärke ähnelt.
        /// </summary>
        internal static string KDS_Strength {
            get {
                return ResourceManager.GetString("KDS_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Vitalität ähnelt.
        /// </summary>
        internal static string KDS_Vitality {
            get {
                return ResourceManager.GetString("KDS_Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KDS: Vitalität / Willenskraft ähnelt.
        /// </summary>
        internal static string KDS_VitalityWisdom {
            get {
                return ResourceManager.GetString("KDS_VitalityWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kenta ähnelt.
        /// </summary>
        internal static string Kentauros {
            get {
                return ResourceManager.GetString("Kentauros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glück ähnelt.
        /// </summary>
        internal static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lydian ähnelt.
        /// </summary>
        internal static string Lydian {
            get {
                return ResourceManager.GetString("Lydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die M. Gen. ähnelt.
        /// </summary>
        internal static string MAcc {
            get {
                return ResourceManager.GetString("MAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die M. Angriff ähnelt.
        /// </summary>
        internal static string MAtk {
            get {
                return ResourceManager.GetString("MAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die M. Abwehr ähnelt.
        /// </summary>
        internal static string MDef {
            get {
                return ResourceManager.GetString("MDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minotaurus ähnelt.
        /// </summary>
        internal static string Minotaurus {
            get {
                return ResourceManager.GetString("Minotaurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MP Erh. ähnelt.
        /// </summary>
        internal static string MPRegen {
            get {
                return ResourceManager.GetString("MPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Karfunkel ähnelt.
        /// </summary>
        internal static string MysticKoala {
            get {
                return ResourceManager.GetString("MysticKoala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tafari ähnelt.
        /// </summary>
        internal static string Naga {
            get {
                return ResourceManager.GetString("Naga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachtmahr ähnelt.
        /// </summary>
        internal static string Nightmare {
            get {
                return ResourceManager.GetString("Nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine ähnelt.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oktopus ähnelt.
        /// </summary>
        internal static string Octopus {
            get {
                return ResourceManager.GetString("Octopus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ork ähnelt.
        /// </summary>
        internal static string Orc {
            get {
                return ResourceManager.GetString("Orc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Panter ähnelt.
        /// </summary>
        internal static string Pantera {
            get {
                return ResourceManager.GetString("Pantera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die P. Angriff ähnelt.
        /// </summary>
        internal static string PAtk {
            get {
                return ResourceManager.GetString("PAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die P. Abwehr ähnelt.
        /// </summary>
        internal static string PDef {
            get {
                return ResourceManager.GetString("PDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geflügel ähnelt.
        /// </summary>
        internal static string Poultry {
            get {
                return ResourceManager.GetString("Poultry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rote Pixie ähnelt.
        /// </summary>
        internal static string RedPixie {
            get {
                return ResourceManager.GetString("RedPixie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Salamander ähnelt.
        /// </summary>
        internal static string Salamander {
            get {
                return ResourceManager.GetString("Salamander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sirene ähnelt.
        /// </summary>
        internal static string Siren {
            get {
                return ResourceManager.GetString("Siren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skelett ähnelt.
        /// </summary>
        internal static string Skeleton {
            get {
                return ResourceManager.GetString("Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schneemann ähnelt.
        /// </summary>
        internal static string Snowman {
            get {
                return ResourceManager.GetString("Snowman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schicksalswürfel ähnelt.
        /// </summary>
        internal static string StoneGolem {
            get {
                return ResourceManager.GetString("StoneGolem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stärke ähnelt.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tortus ähnelt.
        /// </summary>
        internal static string Tortus {
            get {
                return ResourceManager.GetString("Tortus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string UI_About {
            get {
                return ResourceManager.GetString("UI_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DizzySasquatch&apos;s Beltstatcalculator $version$n$nVielen Dank an Grzlgrmpf für die Hilfe beim Testen und Einbringen neuer Ideen. ähnelt.
        /// </summary>
        internal static string UI_AboutText {
            get {
                return ResourceManager.GetString("UI_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über den Beltstatcalculator (by DizzySasquatch) ähnelt.
        /// </summary>
        internal static string UI_AboutTitle {
            get {
                return ResourceManager.GetString("UI_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gürtelverzauberung ähnelt.
        /// </summary>
        internal static string UI_BeltEnhancement {
            get {
                return ResourceManager.GetString("UI_BeltEnhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string UI_Error {
            get {
                return ResourceManager.GetString("UI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache konnte nicht geladen werden. ähnelt.
        /// </summary>
        internal static string UI_LanguageParseError {
            get {
                return ResourceManager.GetString("UI_LanguageParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limit ähnelt.
        /// </summary>
        internal static string UI_Limit {
            get {
                return ResourceManager.GetString("UI_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen ähnelt.
        /// </summary>
        internal static string UI_Reset {
            get {
                return ResourceManager.GetString("UI_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kraftstufe ähnelt.
        /// </summary>
        internal static string UI_Stage {
            get {
                return ResourceManager.GetString("UI_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mechapixie ähnelt.
        /// </summary>
        internal static string Undine {
            get {
                return ResourceManager.GetString("Undine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einhorn ähnelt.
        /// </summary>
        internal static string Unicorn {
            get {
                return ResourceManager.GetString("Unicorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vitalität ähnelt.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weißer Drache ähnelt.
        /// </summary>
        internal static string WhiteDragon {
            get {
                return ResourceManager.GetString("WhiteDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willenskraft ähnelt.
        /// </summary>
        internal static string Wisdom {
            get {
                return ResourceManager.GetString("Wisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wolf ähnelt.
        /// </summary>
        internal static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yeti ähnelt.
        /// </summary>
        internal static string Yeti {
            get {
                return ResourceManager.GetString("Yeti", resourceCulture);
            }
        }
    }
}
